ARG WINDOWS_VERSION=ltsc2025@sha256:6f8cc852e1dc02279f57adfc063b9640dc4e51f5758410e98b116bd919f849bc

FROM mcr.microsoft.com/windows/nanoserver:$WINDOWS_VERSION

WORKDIR /app/

COPY ./aks-node-termination-handler.exe /app/aks-node-termination-handler.exe
USER ContainerUser

ENTRYPOINT [ "/app/aks-node-termination-handler.exe" ]
