on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  validate-license:
    name: validate-license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: ./scripts/validate-license.sh
